name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fecbd57dc76514ae090ca9e04facb3fec574aa7849d0c4e45293de778cda4df"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
