name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcb3bbba0ed28d83d9f7748959063aaf5485d56ee09a9b1559744096c481c2e4"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
