name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df11953fb282fc488a720d26a7e3480010a54827e84a1a247b4a0bf55525e5fa"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
