name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "297e4179229cbfdf2a6cb35dd42c9fcc22297dbe40b813c45aa4552cfe6398ca"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
