name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ae840f4671382f0fd73a7113fd430ed1c22744127b1e36296dda9560a75dd19"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
