name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2c8f34c22d852b842099facd0c2081fda920a83c8991d1dae3999d13d65fdb1"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
