name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe9a16f831cd381de1f09ec544ae06555bcd2dac7a3b6b75bb28c97427305f75"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
