name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce13c4748cffa483c1f10a9fdea28167c06a0535471700ceb4ce00da1cdb6161"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
