name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fed6d446f0a25f098981455571cab2a805f70869c4304801c51c3ba843376804"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
