name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c7f4f887fa648ce0ba60572e2ae45740e439a6e11bab285841eb2d9beef04bb"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
