name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a50e2f60b644a38f0c0b273ad26ddf4a24aa5dfcc6048c1e1f4c988550fa5593"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
