name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "466fec80bf5872c769ab141e02fd0fdd2c10b181605b4a270d5b57182a652a1f"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
