name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cce45182e8a708cc3dd6988affca972937ebac39976c8aa7a6db533b9039d97d"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
