name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "864a34246751e9976f27627155a57c1cff0b7e84f2f7191ffe54344ae16cc85c"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
