name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6897eddc671906b7c60dacb31fbcbdd089c4bdd3e30d78f8c371d6f10a42fc48"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
