name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5001ff6d9c0d3f90d404086d23735ca3e8957934753e7b8772dfd7823a5294b7"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
