name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f2068ca715fcb6c7556727fa4ed009bfe5d9df71939526059484510e7712e4c"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
