name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "641fe72dca0a985eb8b8e43760638c15a3383ffb121016247a5bb5e5d311b029"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
