name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "045ee9e626ea81d7f05f8bc445da65b2b78ff44124fe56e54e7de1bfc7166dd3"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
