name = "FUMA Amane"
author = "ciisaichan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b1760e5d7133de2fcb72011a082e9c3dcb50cb56114bbe6e01b2718fbbf3141"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
