name: index.toml Refresh
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: refresh
  cancel-in-progress: true

jobs:
  refresh-and-push:
    name: refresh and push
    if: ${{ github.actor != 'github-actions[bot]' }}
    environment: Refresh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch main
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup Golang and install packwiz
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.19'
      - run: |
          go install github.com/packwiz/packwiz@latest
      #- name: Packwiz cache
      #  uses: actions/cache@v4
      #  with:
      #    path: |
      #      ~/.cache/packwiz
      #    key: ${{ runner.os }}-packwiz-${{ hashFiles('**/index.toml') }}
      #    restore-keys:
      #      ${{ runner.os }}-packwiz-
      - name: Packwiz refresh
        shell: bash
        run: |
          packwiz refresh
      - name: Setup Git and push
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add index.toml pack.toml
          git commit -m "`date -u`: Automated index refresh by Actions" || true
          git push

